FROM grafana/grafana
USER root
#ADD https://github.com/ravendb/ravendb-grafana-datasource/releases/download/v1.0.0/ravendb-datasource-1.0.0.zip /tmp
RUN wget https://github.com/ravendb/ravendb-grafana-datasource/releases/download/v1.0.0/ravendb-datasource-1.0.0.zip -P /var/lib/grafana/plugins/
RUN unzip /var/lib/grafana/plugins/ravendb-datasource-1.0.0.zip -d /var/lib/grafana/plugins/
RUN rm /var/lib/grafana/plugins/ravendb-datasource-1.0.0.zip
RUN sed -i 's/;allow_loading_unsigned_plugins =/allow_loading_unsigned_plugins = ravendb-datasource/g' /etc/grafana/grafana.ini
USER grafana
EXPOSE 3000
