FROM ravendb/ravendb
RUN apt-get update
RUN apt-get install wget 
RUN apt-get install unzip
RUN wget https://github.com/MrGorillaz/RavenDB_FHSWF/raw/main/RavenDB.zip -P /tmp/ --no-check-certificate
RUN unzip /tmp/RavenDB.zip -d /opt/RavenDB/Server/RavenData/
EXPOSE 8080
EXPOSE 38888
