{
 "title": "Kunden Weltweit",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "from index 'CloneOf/Orders/Category_Product_Orders'\nselect Revenue as Umsatz\n"
    }
   ]
  },
  {
   "title": "Umsatz Produkt",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "from index 'CloneOf/Orders/Category_Product_Orders'\nselect Product,Revenue"
    }
   ]
  },
  {
   "title": "Übersicht Kunden",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "from 'Customer'\ngroup by Country\norder by Costumer_Count as long Desc\nselect count() as Costumer_Count, key() as Label"
    }
   ]
  },
  {
   "title": "Top 10 Kunden: Umsatz",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "queryText": "from index 'Orders/Customer_Orders_Revenue'\norder by Revenue as long desc\nlimit 10"
    },
    {
     "queryText": "declare function getStreet(f) {\n    return f.Street;\n}\n\ndeclare function getTown(f) {\n    return f.Town;\n}\n\ndeclare function Company(f) {\n    return f.Name + \" | \" + f.Country;\n    \n}\n\nFrom \"Orders\" as o\ngroup by o.Customer\nload o.Customer as c\nselect Company(c) as Company,\nc.Country as Country,\ngetStreet(c.Address) as Street,\ngetTown(c.Address) as Town,\nc.Geohash as geohash\nlimit 10"
    }
   ]
  },
  {
   "title": "Top 10: Orders vs. Items",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "declare function Company(f) {\n    return f.Name + \" | \" + f.Country;\n    \n}\n\nFrom \"Orders\" as o\ngroup by o.Customer\norder by ItemsPurchased as long  desc \nload o.Customer as c\nselect Company(c) as Company,\ncount() as NumberOfOrders, \nsum(o.Ordered[].Quantity) as ItemsPurchased\nLimit 10"
    }
   ]
  },
  {
   "title": "Heatmap Kunden",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "queryText": "declare function getStreet(f) {\n    return f.Street;\n}\n\ndeclare function getTown(f) {\n    return f.Town;\n}\n\nFrom \"Orders\" as o\ngroup by o.Customer\nload o.Customer as c\nselect c.Name as Company,\nc.Country as Country,\ngetStreet(c.Address) as Street,\ngetTown(c.Address) as Town,\nc.Geohash as geohash"
    },
    {
     "queryText": "from index 'Orders/Customer_Orders_Revenue'\nselect Revenue as \"Umsatz in €\""
    }
   ]
  },
  {
   "title": "Top 30 Kunden: Umsatz",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "queryText": "from index 'Orders/Customer_Orders_Revenue'\norder by Revenue as long desc\nlimit 30"
    },
    {
     "queryText": "declare function getStreet(f) {\n    return f.Street;\n}\n\ndeclare function getTown(f) {\n    return f.Town;\n}\n\nFrom \"Orders\" as o\ngroup by o.Customer\nload o.Customer as c\nselect c.Name as Company,\nc.Country as Country,\ngetStreet(c.Address) as Street,\ngetTown(c.Address) as Town,\nc.Geohash as geohash\nlimit 30"
    }
   ]
  },
  {
   "title": "Kunden: Anzahl Artikel",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "from index 'Auto/Orders/ByCountAndLines[].QuantityAndOrdered[].QuantityAndQuantityReducedByCustomer' as orders\nload Customer as c\nselect c.Name, c.Country, c.Geohash as geohash, orders.Ordered[].Quantity as quantity"
    }
   ]
  },
  {
   "title": "Kunden: Umsatz",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "queryText": "from index 'Auto/Orders/ByCountAndLines[].QuantityAndOrdered[].QuantityAndQuantityReducedByCustomer' as orders\nload Customer as c\nselect c.Name, c.Country, c.Geohash as geohash"
    },
    {
     "queryText": "from index 'Orders/Customer_Orders_Revenue'\nselect Revenue as \"Umsatz in €\""
    }
   ]
  }
 ]
}